dist: xenial
sudo: false
language: python
matrix:
    include:
      - python: 3.5
        env: TOX_ENV=py35 DOCOV=true
      - python: 3.6
        env: TOX_ENV=py36 DOCOV=false
      - python: 3.7
        env: TOX_ENV=py37 DOCOV=false
      - python: 3.6
        env: TOX_ENV=flake8 DOCOV=false

install: 
  - pip uninstall -y funcsigs || true
  - pip install -U tox-travis coveralls pytest
  - pip install -r requirements_dev.txt

script: 
  - tox -e $TOX_ENV
  - ($DOCOV && ccoverage run --source modpipe -m py.test) || true

after_success: coveralls

before_cache:
  - rm -rf $HOME/.cache/pip/log

cache:
  directories:
    - $HOME/.cache/pip
