environment:
  matrix:
    - PYTHON: "C:\\Python35"
      TOX_ENV: "py35"

    - PYTHON: "C:\\Python36"
      TOX_ENV: "py36"

    - PYTHON: "C:\\Python37"
      TOX_ENV: "py37"

install:
  - "%PYTHON%/Scripts/easy_install -U pip"
  - "%PYTHON%/Scripts/pip install tox wheel"
  - "%PYTHON%/Scripts/pip install -r requirements_dev.txt"

build: false  # Not a C# project, build stuff at the test step instead.

test_script:
  - "%PYTHON%/Scripts/tox -e %TOX_ENV%"
